server:
  port: 9999
  servlet:
    session:
      cookie:
        name: UNSESSION
spring:
  datasource:
    url: jdbc:mysql://47.101.49.146:3306/um?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: um
    password: um123456
    druid:
      max-active: 20
      max-wait: 20000
      min-idle: 1
      filters: stat,wall
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        ddl-auto: none
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.security: debug

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/um?useUnicode=true&characterEncoding=utf8&useSSL=false