server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://user:eureka@127.0.0.1:8761/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: admin
      user.password: admin
spring:
  cloud:
    gateway:
      routes:
      - id: contact
        uri: lb://contact
        predicates:
          - Path= /contact/**
        filters:
          - StripPrefix= 1
debug: true
