server:
  port: 8880
eureka:
  client:
    service-url:
      defaultZone: http://user:eureka@127.0.0.1:8761/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: admin
      user.password: admin
spring:
  security:
    user:
      name: admin
      password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always