server:
  port: 7777
eureka:
  client:
    service-url:
      defaultZone: http://user:eureka@127.0.0.1:8761/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
zuul:
  ignored-services: '*'
  routes:
    contact-servie:
      path: /contact/**
      serviceId: contact
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  server:
    address: 127.0.0.1